-- Japanese Lang cloud sync schema
-- Run this once in Supabase Dashboard → SQL Editor.

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  hard_vocabulary jsonb not null default '[]'::jsonb,
  spaced_repetition jsonb not null default '{}'::jsonb,
  practice_lessons jsonb not null default '[]'::jsonb,
  lesson_filter jsonb not null default '{"selectedLessons":["lesson1"]}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_settings
  add column if not exists lesson_filter jsonb not null default '{"selectedLessons":["lesson1"]}'::jsonb;

alter table public.user_settings enable row level security;

drop policy if exists "Users can read their own settings" on public.user_settings;
create policy "Users can read their own settings"
  on public.user_settings for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own settings" on public.user_settings;
create policy "Users can insert their own settings"
  on public.user_settings for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own settings" on public.user_settings;
create policy "Users can update their own settings"
  on public.user_settings for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists user_settings_updated_at_idx on public.user_settings(updated_at);

-- =====================================================
-- Crash / renderer diagnostics
-- =====================================================
-- The browser may insert diagnostics, but browser clients cannot read them.
-- A GitHub Action uses a server-side Supabase secret to export them to the repo.
create table if not exists public.crash_logs (
  id bigint generated by default as identity primary key,
  session_id text not null,
  detected_at timestamptz not null default now(),
  started_at timestamptz,
  last_seen_at timestamptz,
  possible_crash boolean not null default true,
  context jsonb not null default '{}'::jsonb,
  events jsonb not null default '[]'::jsonb,
  errors jsonb not null default '[]'::jsonb,
  last_event jsonb,
  app_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.crash_logs enable row level security;

drop policy if exists "Browser can submit crash diagnostics" on public.crash_logs;
create policy "Browser can submit crash diagnostics"
  on public.crash_logs for insert
  to anon, authenticated
  with check (true);

-- Explicitly remove client-side read/write privileges except INSERT.
revoke select, update, delete on public.crash_logs from anon, authenticated;
grant insert on public.crash_logs to anon, authenticated;
grant usage, select on sequence public.crash_logs_id_seq to anon, authenticated;

drop index if exists crash_logs_session_id_idx;
create index crash_logs_session_id_idx on public.crash_logs(session_id);
create index crash_logs_detected_at_idx on public.crash_logs(detected_at desc);
