// Japanese Lang — Global Admin Lock
(function(){'use strict';
const SUPABASE_URL='https://levpdywhnikadumfocao.supabase.co';
const SUPABASE_ANON_KEY='REDACTED';
const KEY='japaneseLangAdminSession';
let token='';
let rememberMe=true;
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s&&s.token){token=s.token;rememberMe=true;return true}const ss=JSON.parse(sessionStorage.getItem(KEY)||'null');if(ss&&ss.token){token=ss.token;rememberMe=false;return true}localStorage.removeItem(KEY);sessionStorage.removeItem(KEY)}catch(_){}return false}
function save(){try{localStorage.removeItem(KEY);sessionStorage.removeItem(KEY);const data=JSON.stringify({token});if(rememberMe)localStorage.setItem(KEY,data);else sessionStorage.setItem(KEY,data)}catch(_){}
}
function clear(){token='';try{localStorage.removeItem(KEY);sessionStorage.removeItem(KEY)}catch(_){};window.dispatchEvent(new Event('japaneseAdminChanged'));updateButton()}
async function verify(password){const r=await fetch(SUPABASE_URL+'/functions/v1/manual-input',{method:'POST',headers:{Authorization:'Bearer '+SUPABASE_ANON_KEY,apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({action:'verify',password:String(password||'')})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Incorrect password.');if(!d.token)throw Error('Could not create an admin session.');token=d.token;save();window.dispatchEvent(new Event('japaneseAdminChanged'));updateButton();return token}
async function unlock(password,remember){if(load()){updateButton();return token}let p=password;if(p===undefined||p===null||p==='')p=window.prompt('Enter the Admin password:');if(!p)return '';if(typeof remember==='boolean')rememberMe=remember;return await verify(p)}
function isUnlocked(){if(token)return true;if(load())return true;token='';return false}
function getToken(){return isUnlocked()?token:''}
function lock(){clear()}
function updateButton(){const b=document.getElementById('adminLockButton');if(!b)return;const on=isUnlocked();b.textContent=on?'🔓 Admin':'🔒 Admin';b.setAttribute('aria-label',on?'Lock Admin mode':'Unlock Admin mode');b.title=on?'Lock Admin mode':'Unlock Admin mode'}
function openUnlockModal(){const old=document.getElementById('adminUnlockModal');if(old)old.remove();const wrap=document.createElement('div');wrap.id='adminUnlockModal';wrap.innerHTML='<div class="admin-unlock-overlay"><form class="admin-unlock-box" autocomplete="off"><button type="button" class="admin-unlock-close" aria-label="Close">×</button><h2>🔒 Admin Unlock</h2><label for="adminUnlockPassword">Password</label><input id="adminUnlockPassword" type="password" autocomplete="current-password" spellcheck="false" required><label class="admin-remember-row"><input id="adminRememberMe" type="checkbox" checked> <span>Remember me</span></label><button class="admin-unlock-submit" type="submit">Unlock</button><div class="admin-unlock-status" role="status"></div></form></div>';
const style=document.createElement('style');style.textContent='#adminUnlockModal .admin-unlock-overlay{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(0,0,0,.55)}#adminUnlockModal .admin-unlock-box{position:relative;width:min(390px,100%);box-sizing:border-box;padding:26px 22px;border:1px solid var(--paper-line,#d9d2c3);border-radius:16px;background:var(--paper-cell,#fffdf8);color:var(--ink,#241f18);box-shadow:0 12px 40px rgba(0,0,0,.25);display:flex;flex-direction:column;gap:9px}#adminUnlockModal h2{margin:0 0 8px;font-size:22px}#adminUnlockModal label:not(.admin-remember-row){font-weight:700;font-size:14px}#adminUnlockModal #adminUnlockPassword{box-sizing:border-box;width:100%;min-height:44px;padding:9px 12px;border:1px solid var(--paper-line,#d9d2c3);border-radius:9px;background:var(--paper,#f7f2e7);color:inherit;font:inherit;font-size:16px}.admin-remember-row{display:flex;align-items:center;gap:8px;font-size:14px;cursor:pointer;user-select:none}.admin-remember-row input{width:17px;height:17px;margin:0}.admin-unlock-submit{min-height:44px;border:0;border-radius:9px;padding:9px 16px;background:var(--ink,#241f18);color:var(--paper-cell,#fffdf8);font:inherit;font-weight:700;cursor:pointer}.admin-unlock-close{position:absolute;top:8px;right:10px;border:0;background:transparent;color:inherit;font-size:28px;line-height:1;cursor:pointer}.admin-unlock-status{min-height:20px;font-size:14px;font-weight:700}.admin-unlock-status.error{color:#b42318}';document.head.appendChild(style);document.body.appendChild(wrap);const form=wrap.querySelector('form'),input=wrap.querySelector('#adminUnlockPassword'),remember=wrap.querySelector('#adminRememberMe'),status=wrap.querySelector('.admin-unlock-status');wrap.querySelector('.admin-unlock-close').onclick=()=>wrap.remove();form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('.admin-unlock-submit');b.disabled=true;status.textContent='Checking password...';status.className='admin-unlock-status';try{rememberMe=remember.checked;await unlock(input.value,remember.checked);wrap.remove()}catch(e){status.textContent=e.message||'Could not unlock Admin mode.';status.className='admin-unlock-status error'}finally{b.disabled=false}};input.focus()}
function bind(){const b=document.getElementById('adminLockButton');if(b)b.addEventListener('click',async()=>{if(isUnlocked()){if(window.confirm('Lock Admin mode now?'))lock();return}openUnlockModal()});updateButton()}
window.japaneseAdmin={unlock,isUnlocked,getToken,lock,verify,openUnlockModal};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
