// Japanese Lang — persistent local crash / renderer diagnostics
(() => {
    "use strict";
    const DB_NAME="JapaneseLangDiagnostics", STORE="sessions", KEY="japanese-lang-crash-log-v4";
    const MAX_EVENTS=180, MAX_ERRORS=60;
    const now=()=>new Date().toISOString();
    const safe=(v,n=1800)=>{try{return String(typeof v==="string"?v:JSON.stringify(v)).slice(0,n)}catch(_){return String(v).slice(0,n)}};
    const memory=()=>{try{const m=performance.memory;return m?{limit:m.jsHeapSizeLimit,total:m.totalJSHeapSize,used:m.usedJSHeapSize}:null}catch(_){return null}};
    const context=()=>({href:location.href,path:location.pathname,title:document.title||"",userAgent:navigator.userAgent,platform:navigator.platform||"",language:navigator.language||"",languages:navigator.languages||[],cores:navigator.hardwareConcurrency||null,deviceMemory:navigator.deviceMemory||null,online:navigator.onLine,visibility:document.visibilityState,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1},memory:memory(),at:now()});
    const target=el=>{try{if(!el?.tagName)return null;return{tag:el.tagName,id:el.id||"",classes:typeof el.className==="string"?el.className.slice(0,250):"",aria:el.getAttribute?.("aria-label")||"",text:(el.textContent||"").trim().replace(/\s+/g," ").slice(0,160)}}catch(_){return null}};
    const appState=()=>{const o={};try{for(const k of Object.keys(localStorage))o[k]=(localStorage.getItem(k)||"").slice(0,5000)}catch(_){}return o};
    function db(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(new Error("IndexedDB unavailable"));const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"sessionId"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error("IndexedDB open failed"))})}
    async function idbPut(value){try{const d=await db();await new Promise((res,rej)=>{const tx=d.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close();return true}catch(_){return false}}
    async function idbAll(){try{const d=await db();const rows=await new Promise((res,rej)=>{const r=d.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});d.close();return rows}catch(_){return[]}}
    const oldLocal=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch(_){return null}})();
    let state={sessionId:`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`,startedAt:now(),lastSeenAt:now(),cleanExit:false,context:context(),events:[],errors:[],lastEvent:null};
    function persist(){const copy=JSON.parse(JSON.stringify(state));try{localStorage.setItem(KEY,JSON.stringify(copy))}catch(_){}idbPut(copy)}
    function event(type,details={}){const e={at:now(),type,...details};state.lastSeenAt=e.at;state.lastEvent=e;state.events.push(e);if(state.events.length>MAX_EVENTS)state.events.splice(0,state.events.length-MAX_EVENTS);persist()}
    function error(type,details={}){state.errors.push({at:now(),type,...details});if(state.errors.length>MAX_ERRORS)state.errors.splice(0,state.errors.length-MAX_ERRORS);event(type,details)}
    (async()=>{const previous=oldLocal&&!oldLocal.cleanExit&&oldLocal.events?.length?oldLocal:null;if(previous)await idbPut({...previous,recoveredAt:now(),possibleCrash:true,appStateAtRecovery:appState()});event("session-start",{previousCrashDetected:!!previous,previousSessionId:previous?.sessionId||null})})();
    window.addEventListener("error",e=>{if(e?.target&&e.target!==window)return error("resource-error",{resource:e.target.src||e.target.href||"",target:target(e.target)});error("window-error",{message:safe(e?.message||"Unknown error"),file:safe(e?.filename||""),line:e?.lineno||0,column:e?.colno||0,stack:safe(e?.error?.stack||"")})},true);
    window.addEventListener("unhandledrejection",e=>error("unhandled-rejection",{reason:safe(e?.reason),stack:safe(e?.reason?.stack||"")}));
    ["error","warn"].forEach(level=>{try{const original=console[level];console[level]=function(...args){try{error(`console-${level}`,{message:args.map(a=>safe(a,500)).join(" | ")})}catch(_){}return original.apply(this,args)}}catch(_){}});
    window.addEventListener("online",()=>event("network-online"));window.addEventListener("offline",()=>event("network-offline"));document.addEventListener("visibilitychange",()=>event("visibility",{value:document.visibilityState}));window.addEventListener("pageshow",e=>event("pageshow",{persisted:!!e.persisted}));window.addEventListener("pagehide",e=>event("pagehide",{persisted:!!e.persisted}));document.addEventListener("click",e=>event("click",{target:target(e.target)}),true);document.addEventListener("change",e=>event("change",{target:target(e.target)}),true);window.addEventListener("securitypolicyviolation",e=>error("csp-violation",{blockedURI:e.blockedURI||"",directive:e.violatedDirective||"",sourceFile:e.sourceFile||"",line:e.lineNumber||0,column:e.columnNumber||0}));
    setInterval(()=>{const m=memory();if(m)event("memory-sample",{memory:m})},10000);
    window.addEventListener("beforeunload",()=>{state.cleanExit=true;state.lastSeenAt=now();persist()});
    function downloadBlob(filename,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
    async function downloadCrashLog(){const rows=await idbAll();const crashes=rows.filter(r=>r.possibleCrash||r.recoveredAt||r.previousCrashRecovered);const payload={exportedAt:now(),app:"Japanese Lang",version:4,currentSession:state,crashSessions:crashes,indexedDBSessions:rows};downloadBlob(`japanese-lang-crash-log-${new Date().toISOString().replace(/[:.]/g,"-")}.json`,payload);event("crash-log-downloaded",{sessions:rows.length,crashSessions:crashes.length});return payload}
    function addDownloadButton(){if(document.getElementById("japaneseLangCrashDownload"))return;const b=document.createElement("button");b.id="japaneseLangCrashDownload";b.type="button";b.textContent="Download Crash Log";Object.assign(b.style,{position:"fixed",right:"12px",bottom:"12px",zIndex:"2147483647",display:"none",padding:"9px 12px",border:"0",borderRadius:"8px",font:"600 13px system-ui",cursor:"pointer"});b.addEventListener("click",downloadCrashLog);document.body.appendChild(b);if(oldLocal&&!oldLocal.cleanExit&&oldLocal.events?.length)b.style.display="block"}
    if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",addDownloadButton);else addDownloadButton();
    window.JapaneseLangCrashLogger=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),addEvent:(t,d)=>event(String(t),d||{}),addError:(t,d)=>error(String(t),d||{}),downloadCrashLog,getSessions:idbAll});
})();
