// Japanese Lang — Secure Manual Input
(function(){'use strict';
const SUPABASE_URL='https://levpdywhnikadumfocao.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldnBkeXdobmlrYWR1bWZvY2FvIiwiaWF0IjoxNzg2ODc5NTM1LCJleHAiOjIxMDI0NTUzOTl9.NiBsJ_jEeAPNuDLdjqn9bQamTOz-kgLaLLQPcE6aM';
const TIME_URL=SUPABASE_URL+'/functions/v1/time-date-input';
const WORDS_RAW_URL='https://raw.githubusercontent.com/najmul-hasan-nirob/japanese-lang/main/js/similar%20words/similar-words-lesson.js';
const lock=document.getElementById('manualLock'),unlockForm=document.getElementById('manualUnlockForm'),unlockStatus=document.getElementById('manualUnlockStatus'),form=document.getElementById('manualInputForm'),targetSelect=document.getElementById('manualTarget'),similarFields=document.getElementById('similarFields'),ruleFields=document.getElementById('ruleFields'),timeDateFields=document.getElementById('timeDateFields'),japaneseInput=document.getElementById('manualJapanese'),romajiInput=document.getElementById('manualRomaji'),banglaInput=document.getElementById('manualBangla'),groupInput=document.getElementById('manualGroup'),newGroupInput=document.getElementById('manualNewGroup'),ruleKindInput=document.getElementById('manualRuleKind'),ruleInput=document.getElementById('manualRule'),timeJapanese=document.getElementById('manualTimeJapanese'),timeRomaji=document.getElementById('manualTimeRomaji'),timeBangla=document.getElementById('manualTimeBangla'),timeGroup=document.getElementById('manualTimeGroup'),submitButton=document.getElementById('manualSubmit'),status=document.getElementById('manualStatus'),lockButton=document.getElementById('manualLockButton');
let admin=()=>window.japaneseAdmin;if(!form||!unlockForm)return;
function setStatus(el,msg,type){el.textContent=msg||'';el.className='manual-status'+(type?' '+type:'')}
function normalizeGroup(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,'-')}
function displayGroup(v){return String(v||'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function extractGroups(s){const m=s.match(/const\s+words\s*=\s*\[([\s\S]*?)\n\s*\];/);if(!m)throw Error('Could not find the words array.');const a=[],r=/group\s*:\s*(['"])(.*?)\1/g;let x;while((x=r.exec(m[1])))if(x[2]&&!a.includes(x[2]))a.push(x[2]);return a}
async function loadGroups(){try{groupInput.innerHTML='<option value="" disabled selected>Loading groups...</option>';const r=await fetch(WORDS_RAW_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Could not load groups.');populateGroups(extractGroups(await r.text()))}catch(e){groupInput.innerHTML='<option value="" disabled selected>Could not load groups</option><option value="__create_new__">＋ Create a new group</option>';setStatus(status,e.message,'error')}}
function populateGroups(gs){groupInput.innerHTML='<option value="" disabled>Select a group</option>';gs.forEach(g=>{const o=document.createElement('option');o.value=g;o.textContent=displayGroup(g);groupInput.appendChild(o)});const c=document.createElement('option');c.value='__create_new__';c.textContent='＋ Create a new group';groupInput.appendChild(c);if(gs.length)groupInput.value=gs[0];showNewGroupField()}
function showNewGroupField(){const c=groupInput.value==='__create_new__';newGroupInput.hidden=!c;newGroupInput.required=c;if(c)newGroupInput.focus()}
function updateTarget(){const rules=targetSelect.value==='important-rules',td=targetSelect.value==='time-date-numbers';similarFields.hidden=rules||td;ruleFields.hidden=!rules;timeDateFields.hidden=!td;japaneseInput.required=!rules&&!td;romajiInput.required=!rules&&!td;banglaInput.required=!rules&&!td;groupInput.required=!rules&&!td;newGroupInput.required=!rules&&!td&&groupInput.value==='__create_new__';ruleKindInput.required=rules;ruleInput.required=rules;timeJapanese.required=td;timeRomaji.required=td;timeBangla.required=td;timeGroup.required=td;submitButton.textContent=rules?'Add Rule':td?'Add Time/Date Entry':'Add Word'}
async function request(body){const token=admin()?.getToken();if(!token)throw Error('Admin mode is locked. Unlock Admin mode first.');const endpoint=body.target==='time-date-numbers'?TIME_URL:SUPABASE_URL+'/functions/v1/manual-input';const r=await fetch(endpoint,{method:'POST',headers:{Authorization:'Bearer '+SUPABASE_ANON_KEY,apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json','x-admin-token':token},body:JSON.stringify({...body,adminToken:token})});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)admin()?.lock();throw Error(d.error||('Request failed ('+r.status+').'));}return d}
function showUnlocked(){lock.hidden=true;form.hidden=false;loadGroups();updateTarget()}function showLocked(){form.hidden=true;lock.hidden=false;setStatus(unlockStatus,'','')}
async function unlockAdmin(){try{setStatus(unlockStatus,'Unlocking Admin mode...','');await admin()?.unlock();if(admin()?.isUnlocked())showUnlocked();else setStatus(unlockStatus,'Admin mode was not unlocked.','error')}catch(e){setStatus(unlockStatus,e.message||'Could not unlock Admin mode.','error')}}
targetSelect.addEventListener('change',updateTarget);groupInput.addEventListener('change',showNewGroupField);lockButton.addEventListener('click',()=>{admin()?.lock();showLocked()});unlockForm.addEventListener('submit',async e=>{e.preventDefault();const b=unlockForm.querySelector('button[type="submit"]');b.disabled=true;await unlockAdmin();b.disabled=false});
form.addEventListener('submit',async e=>{e.preventDefault();setStatus(status,'','');if(!admin()?.isUnlocked()){showLocked();return}const target=targetSelect.value;let body={target};if(target==='important-rules'){body.kind=ruleKindInput.value.trim();body.rule=ruleInput.value.trim();if(!body.kind||!body.rule){setStatus(status,'Please complete both Important Rules fields.','error');return}}else if(target==='time-date-numbers'){body={...body,id:'tdn-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),jp:timeJapanese.value.trim(),romaji:timeRomaji.value.trim(),bn:timeBangla.value.trim(),group:timeGroup.value};if(!body.jp||!body.romaji||!body.bn||!body.group){setStatus(status,'Please complete all Time, date & numbers fields.','error');return}}else{body={...body,jp:japaneseInput.value.trim(),romaji:romajiInput.value.trim(),bn:banglaInput.value.trim(),group:normalizeGroup(groupInput.value==='__create_new__'?newGroupInput.value:groupInput.value)};if(!body.jp||!body.romaji||!body.bn||!body.group){setStatus(status,'Please complete all fields.','error');return}}submitButton.disabled=true;try{setStatus(status,'Adding securely...','');const d=await request(body);setStatus(status,d.message||'Added successfully.','success');form.reset();updateTarget();if(target==='similar-words')await loadGroups()}catch(x){setStatus(status,x.message,'error');if(/admin session|locked|expired/i.test(x.message||''))showLocked()}finally{submitButton.disabled=false;updateTarget()}});
document.addEventListener('japaneseAdminChanged',()=>{if(admin()?.isUnlocked())showUnlocked();else showLocked()});if(admin()?.isUnlocked())showUnlocked();else showLocked();
})();
