/* Vocabulary clues — persistent storage through the Supabase Edge Function. */
(function(){
'use strict';
const API='https://levpdywhnikadumfocao.supabase.co/functions/v1/vocabulary-clues';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function identity(card){const lesson=card.querySelector('.lesson-tag')?.textContent?.trim()||'';const romaji=card.dataset.romaji||'';const english=card.querySelector('.english')?.textContent?.trim()||'';const front=card.querySelector('.front>div')?.textContent?.trim()||'';return {lesson,romaji,english,front};}
function cardKey(card){const i=identity(card);return [i.lesson,i.romaji,i.english,i.front].join('|');}
function url(card){return API+'?card_key='+encodeURIComponent(cardKey(card));}
async function load(card){try{const r=await fetch(url(card),{method:'GET',cache:'no-store'});if(!r.ok)return '';const d=await r.json();const clue=d?.clue||'';card.dataset.vocabularyClue=clue;card.classList.toggle('has-vocabulary-clue',!!clue);return clue;}catch(e){console.warn('Vocabulary clue load failed',e);return '';}}
async function save(card,clue){const i=identity(card);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({card_key:cardKey(card),lesson:i.lesson,vocabulary:i.front,clue})});let data=null;try{data=await r.json()}catch(e){}if(!r.ok)throw new Error(data?.error||('HTTP '+r.status));card.dataset.vocabularyClue=data?.clue||clue;card.classList.toggle('has-vocabulary-clue',true);}
async function remove(card){const r=await fetch(url(card),{method:'DELETE'});let data=null;try{data=await r.json()}catch(e){}if(!r.ok)throw new Error(data?.error||('HTTP '+r.status));card.dataset.vocabularyClue='';card.classList.remove('has-vocabulary-clue');}
let activeOverlay=null,activeCard=null,repositionHandler=null;
function destroyOverlay(){if(repositionHandler){window.removeEventListener('scroll',repositionHandler,true);window.removeEventListener('resize',repositionHandler);repositionHandler=null;}if(activeOverlay){activeOverlay.remove();activeOverlay=null;}activeCard=null;}
function mobileRowBounds(card){const grid=document.getElementById('grid');if(!grid)return null;const cards=[...grid.querySelectorAll(':scope>.card')];const r=card.getBoundingClientRect();const rowCards=cards.filter(c=>{const cr=c.getBoundingClientRect();return Math.abs(cr.top-r.top)<=3&&cr.width>0&&cr.height>0;});if(rowCards.length<2)return null;const rects=rowCards.map(c=>c.getBoundingClientRect());return {left:Math.min(...rects.map(x=>x.left)),top:Math.min(...rects.map(x=>x.top)),right:Math.max(...rects.map(x=>x.right)),bottom:Math.max(...rects.map(x=>x.bottom))};}
function positionOverlay(box,card){if(!box||!card||!document.body.contains(card))return;const r=card.getBoundingClientRect(),margin=6;let left,width,desiredTop,rowHeight=null;const isMobile=window.innerWidth<=520;if(isMobile){const row=mobileRowBounds(card);if(row){left=row.left;width=row.right-row.left;desiredTop=row.top;rowHeight=row.bottom-row.top;}else{left=Math.max(margin,r.left);width=Math.min(r.width,window.innerWidth-margin*2);desiredTop=r.top;}}else{left=Math.max(margin,Math.min(r.left,window.innerWidth-r.width-margin));width=Math.min(r.width,window.innerWidth-margin*2);if(width<220){width=Math.min(320,window.innerWidth-margin*2);left=(window.innerWidth-width)/2;}desiredTop=r.top+44;}box.style.left=Math.round(left)+'px';box.style.width=Math.round(width)+'px';box.style.top=Math.round(desiredTop)+'px';if(isMobile&&rowHeight!==null)box.style.height=Math.round(rowHeight)+'px';else box.style.height='';if(!isMobile){const h=box.getBoundingClientRect().height;if(desiredTop+h>window.innerHeight-margin&&r.top-h-margin>margin)box.style.top=Math.round(r.top-h-margin)+'px';}}
function mountOverlay(box,card){destroyOverlay();activeOverlay=box;activeCard=card;document.body.appendChild(box);positionOverlay(box,card);repositionHandler=()=>positionOverlay(box,card);window.addEventListener('scroll',repositionHandler,true);window.addEventListener('resize',repositionHandler);}
function showClue(card){if(activeOverlay&&activeCard===card){destroyOverlay();return;}const clue=card.dataset.vocabularyClue||'';const panel=document.createElement('div');panel.className='vocabulary-clue-panel';panel.innerHTML=`<div class="clue-view-head"><span>💡 Clue</span><button type="button" class="clue-close" aria-label="Close">×</button></div><div class="vocabulary-clue-text">${esc(clue||'No clue yet.')}</div><button type="button" class="clue-edit">Edit</button>`;mountOverlay(panel,card);panel.querySelector('.clue-close').onclick=e=>{e.preventDefault();e.stopPropagation();destroyOverlay();};panel.querySelector('.clue-edit').onclick=e=>{e.preventDefault();e.stopPropagation();showEditor(card);};}
function showEditor(card){const old=card.dataset.vocabularyClue||'',box=document.createElement('div');box.className='vocabulary-clue-editor';box.innerHTML=`<div class="clue-editor-head"><span>💡 Edit clue</span><button type="button" class="clue-close" aria-label="Close">×</button></div><textarea maxlength="500" placeholder="Write a clue..."></textarea><div class="clue-editor-actions"><button type="button" class="clue-save">Save</button><button type="button" class="clue-delete">Delete</button></div>`;mountOverlay(box,card);const ta=box.querySelector('textarea');ta.value=old;ta.focus();ta.setSelectionRange(ta.value.length,ta.value.length);positionOverlay(box,card);box.addEventListener('click',e=>e.stopPropagation());box.querySelector('.clue-close').onclick=e=>{e.preventDefault();e.stopPropagation();destroyOverlay();};box.querySelector('.clue-save').onclick=async()=>{const v=ta.value.trim(),btn=box.querySelector('.clue-save');btn.disabled=true;try{if(v)await save(card,v);else await remove(card);destroyOverlay();if(v)showClue(card);}catch(err){console.error('Vocabulary clue save failed:',err);alert('Could not save clue. Please try again.\n\n'+err.message);btn.disabled=false;}};box.querySelector('.clue-delete').onclick=async()=>{const btn=box.querySelector('.clue-delete');btn.disabled=true;try{await remove(card);destroyOverlay();}catch(err){console.error('Vocabulary clue delete failed:',err);alert('Could not delete clue. Please try again.\n\n'+err.message);btn.disabled=false;}};}
function setup(card){if(!card.querySelector('.vocabulary-back')||card.querySelector('.vocabulary-clue-btn'))return;const bar=card.querySelector('.lesson-card-topbar');if(!bar)return;const b=document.createElement('button');b.type='button';b.className='vocabulary-clue-btn';b.innerHTML='';b.title='Show clue';b.setAttribute('aria-label','Show clue');bar.appendChild(b);load(card);b.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();if(!card.dataset.vocabularyClue)await load(card);showClue(card);});}
function all(){document.querySelectorAll('#grid>.card').forEach(setup)}
function styles(){if(document.getElementById('vocabulary-clue-styles'))return;const s=document.createElement('style');s.id='vocabulary-clue-styles';s.textContent=`
.vocabulary-clue-btn{grid-column:2!important;grid-row:1!important;margin:0!important;padding:0 5px!important;border:0!important;background:transparent!important;color:#fff!important;font-size:0!important;line-height:1!important;cursor:pointer!important;pointer-events:auto!important;width:auto!important;height:auto!important;box-shadow:none!important}.vocabulary-clue-btn::before{content:'💭';font-size:17px!important}.has-vocabulary-clue .vocabulary-clue-btn::before{content:'💡';font-size:17px!important}.has-vocabulary-clue .vocabulary-clue-btn{filter:saturate(1.25)}
.vocabulary-clue-panel,.vocabulary-clue-editor{position:fixed!important;z-index:2147483647!important;top:0;left:0;width:auto;max-width:calc(100vw - 12px)!important;max-height:calc(100vh - 12px)!important;overflow:auto!important;background:#18212c!important;color:#fff!important;padding:2px 15px!important;border-radius:9px!important;box-shadow:0 8px 28px rgba(0,0,0,.55)!important;box-sizing:border-box!important}.vocabulary-clue-panel{text-align:center!important}.clue-view-head,.clue-editor-head{display:flex!important;align-items:center!important;justify-content:space-between!important;font-size:13px!important;margin-bottom:7px!important}.vocabulary-clue-text{font-size:15px!important;line-height:1.45!important;white-space:pre-wrap!important;overflow-wrap:anywhere!important;word-break:break-word!important}.clue-edit{display:inline-block!important;visibility:visible!important;opacity:1!important;margin-top:9px!important;padding:6px 16px!important;border:0!important;border-radius:6px!important;cursor:pointer!important}.clue-close{border:0!important;background:transparent!important;color:#fff!important;font-size:23px!important;line-height:1!important;cursor:pointer!important;padding:0 3px!important}.vocabulary-clue-editor textarea{display:block!important;width:100%!important;min-width:0!important;height:90px!important;box-sizing:border-box!important;resize:vertical!important;padding:8px!important;border-radius:6px!important;border:1px solid #66717d!important;font:inherit!important;line-height:1.4!important}.clue-editor-actions{display:flex!important;align-items:center!important;gap:7px!important;margin-top:9px!important}.clue-editor-actions button{display:inline-flex!important;align-items:center!important;justify-content:center!important;visibility:visible!important;opacity:1!important;flex:0 0 auto!important;min-width:64px!important;padding:7px 13px!important;border:0!important;border-radius:6px!important;cursor:pointer!important}
@media(max-width:520px){.vocabulary-clue-btn::before{font-size:16px!important}.vocabulary-clue-panel,.vocabulary-clue-editor{max-width:calc(100vw - 12px)!important;max-height:calc(100vh - 12px)!important}.vocabulary-clue-panel{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;text-align:center!important}.vocabulary-clue-panel .clue-view-head{position:absolute!important;top:11px!important;left:11px!important;right:11px!important}.vocabulary-clue-panel .vocabulary-clue-text{display:flex!important;align-items:center!important;justify-content:center!important;flex:0 0 auto!important;width:100%!important;text-align:center!important}.vocabulary-clue-panel .clue-edit{align-self:center!important;margin-top:12px!important}.vocabulary-clue-editor textarea{height:90px!important;max-height:35vh!important}}
`;document.head.appendChild(s)}
function init(){styles();all();document.addEventListener('lessonCardsRendered',()=>setTimeout(all,30));const grid=document.getElementById('grid');if(grid)new MutationObserver(()=>setTimeout(all,0)).observe(grid,{childList:true,subtree:true});document.addEventListener('click',e=>{if(activeOverlay&&!activeOverlay.contains(e.target)&&!e.target.closest('.vocabulary-clue-btn'))destroyOverlay()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
