/* Vocabulary clues — local persistence until a secure GitHub/Supabase write endpoint is configured. */
(function(){'use strict';
const KEY='japanese-lang-vocabulary-clues-v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
const write=o=>{try{localStorage.setItem(KEY,JSON.stringify(o))}catch(e){}};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function key(card){return [card.dataset.lesson||'',card.dataset.type||'vocabulary',card.dataset.romaji||'',card.querySelector('.english')?.textContent||'',card.querySelector('.front>div')?.textContent||''].join('|')}
function setup(card){if(!card.querySelector('.vocabulary-back')||card.querySelector('.vocabulary-clue-btn'))return;const bar=card.querySelector('.lesson-card-topbar');if(!bar)return;const b=document.createElement('button');b.type='button';b.className='vocabulary-clue-btn';b.textContent='✎';b.title='Add or edit clue';b.setAttribute('aria-label','Add or edit clue');bar.appendChild(b);const k=key(card),data=read();if(data[k])card.classList.add('has-vocabulary-clue');b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();let box=card.querySelector('.vocabulary-clue-editor');if(box){box.remove();return}box=document.createElement('div');box.className='vocabulary-clue-editor';box.innerHTML='<textarea maxlength="500" placeholder="Write a clue...">'+esc(data[k]||'')+'</textarea><div><button type="button" class="clue-save">Save</button><button type="button" class="clue-delete">Delete</button></div>';card.appendChild(box);const ta=box.querySelector('textarea');ta.focus();box.querySelector('.clue-save').onclick=()=>{const v=ta.value.trim();const all=read();if(v)all[k]=v;else delete all[k];write(all);box.remove();card.classList.toggle('has-vocabulary-clue',!!v)};box.querySelector('.clue-delete').onclick=()=>{const all=read();delete all[k];write(all);box.remove();card.classList.remove('has-vocabulary-clue')};});}
function all(){document.querySelectorAll('#grid>.card').forEach(setup)}
function styles(){if(document.getElementById('vocabulary-clue-styles'))return;const s=document.createElement('style');s.id='vocabulary-clue-styles';s.textContent='.vocabulary-clue-btn{grid-column:1;grid-row:1;margin-left:42px!important;pointer-events:auto;border:0;background:transparent;color:#fff;font-size:20px;cursor:pointer}.has-vocabulary-clue .vocabulary-clue-btn{color:#ffd166}.vocabulary-clue-editor{position:absolute;z-index:100;top:45px;left:8px;right:8px;background:#18212c;padding:10px;border-radius:8px;box-shadow:0 4px 18px #0008}.vocabulary-clue-editor textarea{width:100%;min-height:70px;box-sizing:border-box}.vocabulary-clue-editor div{display:flex;gap:6px;margin-top:6px}.vocabulary-clue-editor button{padding:5px 10px;cursor:pointer}';document.head.appendChild(s)}
function init(){styles();all();document.addEventListener('lessonCardsRendered',()=>setTimeout(all,30));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();