/* Vocabulary clues — persistent storage through the Supabase Edge Function. */
(function(){'use strict';
const API='https://levpdywhnikadumfocao.supabase.co/functions/v1/vocabulary-clues';
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function identity(card){const lesson=card.querySelector('.lesson-tag')?.textContent?.trim()||'';const romaji=card.dataset.romaji||'';const english=card.querySelector('.english')?.textContent?.trim()||'';const front=card.querySelector('.front>div')?.textContent?.trim()||'';return {lesson,romaji,english,front};}
function cardKey(card){const i=identity(card);return [i.lesson,i.romaji,i.english,i.front].join('|');}
function url(card){return API+'?card_key='+encodeURIComponent(cardKey(card));}
function deviceId(){let id='';try{id=localStorage.getItem('japanese-lang-vocabulary-device')||'';if(!id&&crypto?.randomUUID){id=crypto.randomUUID();localStorage.setItem('japanese-lang-vocabulary-device',id)}}catch(e){}return id;}
async function load(card){try{const r=await fetch(url(card));if(!r.ok)return '';const d=await r.json();const clue=d?.clue||'';card.dataset.vocabularyClue=clue;card.classList.toggle('has-vocabulary-clue',!!clue);return clue}catch(e){console.warn('Vocabulary clue load failed',e);return ''}}
async function save(card,clue){const i=identity(card);const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({card_key:cardKey(card),lesson:i.lesson,vocabulary:i.front,clue:clue})});if(!r.ok)throw new Error('save failed');card.dataset.vocabularyClue=clue;card.classList.toggle('has-vocabulary-clue',!!clue)}
async function remove(card){const r=await fetch(url(card),{method:'DELETE'});if(!r.ok)throw new Error('delete failed');card.dataset.vocabularyClue='';card.classList.remove('has-vocabulary-clue')}
function setup(card){if(!card.querySelector('.vocabulary-back')||card.querySelector('.vocabulary-clue-btn'))return;const bar=card.querySelector('.lesson-card-topbar');if(!bar)return;const b=document.createElement('button');b.type='button';b.className='vocabulary-clue-btn';b.textContent='✎';b.title='Add or edit clue';b.setAttribute('aria-label','Add or edit clue');bar.appendChild(b);load(card);b.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();let box=card.querySelector('.vocabulary-clue-editor');if(box){box.remove();return}const old=card.dataset.vocabularyClue||await load(card)||'';box=document.createElement('div');box.className='vocabulary-clue-editor';box.innerHTML='<textarea maxlength="500" placeholder="Write a clue...">'+esc(old)+'</textarea><div><button type="button" class="clue-save">Save</button><button type="button" class="clue-delete">Delete</button></div>';card.appendChild(box);const ta=box.querySelector('textarea');ta.focus();box.querySelector('.clue-save').onclick=async()=>{const v=ta.value.trim(),btn=box.querySelector('.clue-save');btn.disabled=true;try{if(v)await save(card,v);else await remove(card);box.remove()}catch(err){console.error(err);alert('Could not save clue. Please try again.');btn.disabled=false}};box.querySelector('.clue-delete').onclick=async()=>{const btn=box.querySelector('.clue-delete');btn.disabled=true;try{await remove(card);box.remove()}catch(err){console.error(err);alert('Could not delete clue. Please try again.');btn.disabled=false}};});}
function all(){document.querySelectorAll('#grid>.card').forEach(setup)}
function styles(){if(document.getElementById('vocabulary-clue-styles'))return;const s=document.createElement('style');s.id='vocabulary-clue-styles';s.textContent='.vocabulary-clue-btn{grid-column:2;grid-row:1;margin:0!important;padding:0 5px;border:0;background:transparent;color:#fff;font-size:18px;line-height:1;cursor:pointer;pointer-events:auto}.has-vocabulary-clue .vocabulary-clue-btn{color:#ffd166}.vocabulary-clue-editor{position:absolute;z-index:100;top:45px;left:8px;right:8px;background:#18212c;padding:10px;border-radius:8px;box-shadow:0 4px 18px #0008}.vocabulary-clue-editor textarea{width:100%;min-height:70px;box-sizing:border-box;resize:vertical}.vocabulary-clue-editor div{display:flex;gap:6px;margin-top:6px}.vocabulary-clue-editor button{padding:5px 10px;cursor:pointer}.vocabulary-clue-editor button:disabled{opacity:.6;cursor:wait}';document.head.appendChild(s)}
function init(){styles();all();document.addEventListener('lessonCardsRendered',()=>setTimeout(all,30));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();