(function () {
    function init() {
        const grid=document.getElementById('kanjiGrid'), search=document.getElementById('kanjiSearch'), clear=document.getElementById('kanjiSearchClear'), levelPanel=document.getElementById('kanjiLevelPanel'), levelBtn=document.getElementById('kanjiLevelBtn'), mode=document.getElementById('kanjiMode'), shuffleBtn=document.getElementById('kanjiShuffleBtn'), count=document.getElementById('kanjiCount');
        if(!grid||!levelPanel||!search||!clear||!mode||!shuffleBtn||!count||!Array.isArray(window.kanjiData)) return;
        const mnemonicFiles={'山':'01.webp','川':'02.webp','田':'03.webp','日':'04.webp','月':'05.webp','火':'06.webp','水':'07.webp','木':'08.webp','金':'09.webp','土':'10.webp','一':'11.webp','二':'12.webp','三':'13.webp','四':'14.webp','五':'15.webp','六':'16.webp','七':'17.webp','八':'18.webp','九':'19.webp','十':'20.webp','百':'21.webp','千':'22.webp','万':'23.webp','円':'24.webp','年':'25.webp','上':'26.webp','下':'27.webp','中':'28.webp','半':'29.webp','分':'30.webp','人':'31.webp','子':'32.webp','女':'33.webp','男':'34.webp','目':'35.webp','口':'36.webp','耳':'37.webp','手':'38.webp','足':'39.webp','力':'40.webp'};
        const mnemonicBase='/japanese-lang/assets/kanji-mnemonics/';
        const cards=window.kanjiData.map(function(item,index){const no=item.no||index+1,extra=(window.n5KanjiBangla&&window.n5KanjiBangla[item.kanji])||{},has=Object.prototype.hasOwnProperty.call(mnemonicFiles,item.kanji);return{no:no,kanji:item.kanji||'',level:item.level||'N5',kunyomi:item.kunyomi||'',onyomi:item.onyomi||'',reading:item.reading||'',meaning:extra.meaning||item.meaning||'',mnemonicImage:has?mnemonicFiles[item.kanji]:'',banglaExamples:has&&Array.isArray(extra.examples)?extra.examples:[]};}).filter(function(item){return item.kanji;});
        function esc(v){return String(v==null?'':v).replace(/[&<>\\'\"]/g,function(ch){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch];});}
        function selectedLevels(){return Array.from(levelPanel.querySelectorAll('input[type="checkbox"]:checked')).map(function(x){return x.value;});}
        function updateLevelLabel(){const selected=selectedLevels(),all=Array.from(levelPanel.querySelectorAll('input[type="checkbox"]'));levelBtn.textContent=selected.length===all.length?'N5 + N4':selected.length?selected.join(' + '):'None';}
        function filtered(){const q=search.value.trim().toLowerCase(),levels=selectedLevels();return cards.filter(function(item){if(levels.length&&!levels.includes(item.level))return false;if(!q)return true;return[item.kanji,item.kunyomi,item.onyomi,item.reading,item.meaning,item.level,String(item.no)].join(' ').toLowerCase().includes(q);});}
        function details(item){let html=item.meaning?'<div class="kanji-detail-meaning">'+esc(item.meaning)+'</div>':'';html+='<div class="kanji-reading-line"><span class="kanji-reading-label">Kunyomi:</span> '+(item.kunyomi?esc(item.kunyomi):'—')+'</div>';html+='<div class="kanji-reading-line"><span class="kanji-reading-label">Onyomi:</span> '+(item.onyomi?esc(item.onyomi):'—')+'</div>';if(item.banglaExamples.length){html+='<div class="kanji-bangla-examples"><div class="kanji-examples-title">উদাহরণ:</div>';html+=item.banglaExamples.map(function(ex){return'<div class="kanji-example-line"><span class="kanji-example-jp">'+esc(ex.jp)+'</span> — <span class="kanji-example-bn">'+esc(ex.bn)+'</span></div>';}).join('')+'</div>';}return html;}
        function render(){let visible=filtered();if(mode.value==='shuffle')visible=visible.slice().sort(function(){return Math.random()-0.5;});grid.innerHTML=visible.map(function(item){let image=item.mnemonicImage?'<div class="kanji-mnemonic-wrap"><img class="kanji-mnemonic-image" src="'+mnemonicBase+item.mnemonicImage+'?v=3" alt="'+esc(item.kanji)+' mnemonic image" loading="lazy" decoding="async"><span class="kanji-mnemonic-fallback">Mnemonic image</span></div>':'';return'<div class="card kanji-card" data-no="'+item.no+'" data-level="'+esc(item.level)+'" data-kanji="'+esc(item.kanji)+'"><div class="inner"><div class="front"><div class="kanji-character">'+esc(item.kanji)+'</div></div><div class="back">'+image+'<div class="kanji-character small">'+esc(item.kanji)+'</div><div class="kanji-details">'+details(item)+'</div></div></div></div>';}).join('');grid.querySelectorAll('.card').forEach(function(card){card.addEventListener('click',function(){card.classList.toggle('flipped');});});grid.querySelectorAll('.kanji-mnemonic-image').forEach(function(img){img.addEventListener('error',function(){img.parentElement.classList.add('image-error');});});count.textContent='Showing '+visible.length+' kanji';clear.hidden=!search.value;}
        levelBtn.addEventListener('click',function(e){e.stopPropagation();const open=levelPanel.classList.toggle('open');levelBtn.setAttribute('aria-expanded',String(open));});levelPanel.addEventListener('click',function(e){e.stopPropagation();});levelPanel.addEventListener('change',function(){updateLevelLabel();render();});document.addEventListener('click',function(){levelPanel.classList.remove('open');levelBtn.setAttribute('aria-expanded','false');});search.addEventListener('input',render);clear.addEventListener('click',function(){search.value='';render();search.focus();});mode.addEventListener('change',render);shuffleBtn.addEventListener('click',function(){mode.value='shuffle';render();});updateLevelLabel();render();
    }
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
