const kanjiCharacters = "人日一二三四五六七八九十月火水木金土百千万円行来休見今大小上下中右左山川白本子男女父母友先生学校何時間分半毎年前後午名車天気電話食聞書読国外語入出雨東西南北長高口目手足近有花赤紙買朝昼夕夜私家会社店飲多少古新広安立知言思歩走住空週魚耳銀道駅曜作使待力不心文元音楽持映画料理方台字主以去正田同早明牛肉世界仕事工場屋旅動勉強考送売始終計兄弟姉妹代用自地図館英鉄町京味度風洋茶鳥堂室色青黒品物注意医者病院急春夏秋冬親切特別写真運転質問題答教習起死悪重発帰通開集歌着貸借犬服建海員族飯野菜止漢研究試験内体全回所公園利便頭部祖業太低短好若弱軽遠暑寒合伝決困返泳消忘呼閉引押拾捨説受取席連座変乗降働残調続練落寝遅顔首声都県区市村民産林森池門薬洗進暗光線";

// N5 readings sourced from the uploaded Basic Kanji 320 / N5 PDF.
// The order remains exactly the same as the existing kanjiCharacters registry.
const n5KanjiDetails = {
  1:   { kunyomi: "ひと", onyomi: "ジン、ニン" },
  2:   { kunyomi: "ひ、か", onyomi: "ニチ" },
  3:   { kunyomi: "ひと（つ）", onyomi: "イチ、イッ" },
  4:   { kunyomi: "ふた（つ）", onyomi: "ニ" },
  5:   { kunyomi: "みっ（つ）", onyomi: "サン" },
  6:   { kunyomi: "よっ（つ）、よん、よ", onyomi: "シ" },
  7:   { kunyomi: "いつ（つ）", onyomi: "ゴ" },
  8:   { kunyomi: "むっ（つ）", onyomi: "ロク" },
  9:   { kunyomi: "なな（つ）、なな", onyomi: "シチ" },
  10:  { kunyomi: "やっ（つ）", onyomi: "ハチ" },
  11:  { kunyomi: "ここの（つ）", onyomi: "キュウ、ク" },
  12:  { kunyomi: "とお", onyomi: "ジュウ" },
  13:  { kunyomi: "つき", onyomi: "ゲツ、ガツ" },
  14:  { kunyomi: "ひ", onyomi: "カ" },
  15:  { kunyomi: "みず", onyomi: "スイ" },
  16:  { kunyomi: "き", onyomi: "モク" },
  17:  { kunyomi: "かね", onyomi: "キン" },
  18:  { kunyomi: "つち", onyomi: "ド" },
  19:  { kunyomi: "", onyomi: "ヒャク" },
  20:  { kunyomi: "", onyomi: "セン" },
  21:  { kunyomi: "", onyomi: "マン" },
  22:  { kunyomi: "", onyomi: "エン" },
  23:  { kunyomi: "い（きます）、おこな（います）", onyomi: "コウ" },
  24:  { kunyomi: "き（ます）", onyomi: "ライ" },
  25:  { kunyomi: "やす（みます）", onyomi: "" },
  26:  { kunyomi: "み（ます）、み（えます）、み（せます）", onyomi: "ケン" },
  27:  { kunyomi: "いま", onyomi: "コン" },
  28:  { kunyomi: "おお（きい）", onyomi: "ダイ、タイ" },
  29:  { kunyomi: "ちい（さい）、こ", onyomi: "ショウ" },
  30:  { kunyomi: "うえ、あ（げます）、あ（がります）", onyomi: "ジョウ" },
  31:  { kunyomi: "した、さ（げます）、さ（がります）", onyomi: "カ" },
  32:  { kunyomi: "なか", onyomi: "チュウ" },
  33:  { kunyomi: "みぎ", onyomi: "" },
  34:  { kunyomi: "ひだり", onyomi: "" },
  35:  { kunyomi: "やま", onyomi: "サン" },
  36:  { kunyomi: "かわ", onyomi: "" },
  37:  { kunyomi: "しろ（い）、しろ", onyomi: "" },
  38:  { kunyomi: "", onyomi: "ホン" },
  39:  { kunyomi: "こ", onyomi: "" },
  40:  { kunyomi: "おとこ", onyomi: "ダン" },
  41:  { kunyomi: "おんな", onyomi: "ジョ" },
  42:  { kunyomi: "ちち", onyomi: "フ" },
  43:  { kunyomi: "はは", onyomi: "ボ" },
  44:  { kunyomi: "とも", onyomi: "" },
  45:  { kunyomi: "さき", onyomi: "セン" },
  46:  { kunyomi: "い（きます）、う（まれます）、なま", onyomi: "セイ、ショウ" },
  47:  { kunyomi: "まな（びます）", onyomi: "ガク" },
  48:  { kunyomi: "", onyomi: "コウ" },
  49:  { kunyomi: "なに、なん", onyomi: "" },
  50:  { kunyomi: "とき", onyomi: "ジ" },
  51:  { kunyomi: "あいだ、ま", onyomi: "カン" },
  52:  { kunyomi: "わ（けます）", onyomi: "フン、ブン" },
  53:  { kunyomi: "", onyomi: "ハン" },
  54:  { kunyomi: "", onyomi: "マイ" },
  55:  { kunyomi: "とし", onyomi: "ネン" },
  56:  { kunyomi: "まえ", onyomi: "ゼン" },
  57:  { kunyomi: "うし（ろ）、あと", onyomi: "ゴ" },
  58:  { kunyomi: "", onyomi: "ゴ" },
  59:  { kunyomi: "な", onyomi: "メイ" },
  60:  { kunyomi: "くるま", onyomi: "シャ" },
  61:  { kunyomi: "", onyomi: "テン" },
  62:  { kunyomi: "", onyomi: "キ" },
  63:  { kunyomi: "", onyomi: "デン" },
  64:  { kunyomi: "はな（します）、はなし", onyomi: "ワ" },
  65:  { kunyomi: "た（べます）", onyomi: "ショク" },
  66:  { kunyomi: "き（きます）、き（こえます）", onyomi: "ブン" },
  67:  { kunyomi: "か（きます）", onyomi: "ショ" },
  68:  { kunyomi: "よ（みます）", onyomi: "ドク" },
  69:  { kunyomi: "くに", onyomi: "コク" },
  70:  { kunyomi: "そと", onyomi: "ガイ" },
  71:  { kunyomi: "", onyomi: "ゴ" },
  72:  { kunyomi: "い（れます）、はい（ります）", onyomi: "ニュウ" },
  73:  { kunyomi: "だ（します）、で（ます）", onyomi: "シュツ" },
  74:  { kunyomi: "あめ", onyomi: "" },
  75:  { kunyomi: "ひがし", onyomi: "トウ" },
  76:  { kunyomi: "にし", onyomi: "セイ、サイ" },
  77:  { kunyomi: "みなみ", onyomi: "ナン" },
  78:  { kunyomi: "きた", onyomi: "ホク" },
  79:  { kunyomi: "なが（い）", onyomi: "チョウ" },
  80:  { kunyomi: "たか（い）", onyomi: "コウ" },
  81:  { kunyomi: "くち", onyomi: "コウ" },
  82:  { kunyomi: "め", onyomi: "" },
  83:  { kunyomi: "て", onyomi: "シュ" },
  84:  { kunyomi: "あし、た（ります）", onyomi: "" },
  85:  { kunyomi: "ちか（い）", onyomi: "キン" },
  86:  { kunyomi: "あ（ります）", onyomi: "ユウ" },
  87:  { kunyomi: "はな", onyomi: "カ" },
  88:  { kunyomi: "あか（い）、あか", onyomi: "" },
  89:  { kunyomi: "かみ", onyomi: "" },
  90:  { kunyomi: "か（います）", onyomi: "" },
  91:  { kunyomi: "あさ", onyomi: "" },
  92:  { kunyomi: "ひる", onyomi: "" },
  93:  { kunyomi: "ゆう", onyomi: "" },
  94:  { kunyomi: "よる", onyomi: "ヤ" },
  95:  { kunyomi: "わたし、わたくし（formal）", onyomi: "" },
  96:  { kunyomi: "いえ", onyomi: "カ" },
  97:  { kunyomi: "あ（います）", onyomi: "カイ" },
  98:  { kunyomi: "", onyomi: "シャ" },
  99:  { kunyomi: "みせ", onyomi: "テン" },
  100: { kunyomi: "の（みます）", onyomi: "" },
  101: { kunyomi: "おお（い）", onyomi: "" },
  102: { kunyomi: "すこ（し）、すく（ない）", onyomi: "ショウ" },
  103: { kunyomi: "ふる（い）", onyomi: "" },
  104: { kunyomi: "あたら（しい）", onyomi: "シン" },
  105: { kunyomi: "ひろ（い）", onyomi: "" },
  106: { kunyomi: "やす（い）", onyomi: "アン" },
  107: { kunyomi: "た（ちます）", onyomi: "" },
  108: { kunyomi: "し（ります）", onyomi: "" },
  109: { kunyomi: "い（います）、こと", onyomi: "ゴン" },
  110: { kunyomi: "おも（います）", onyomi: "" },
  111: { kunyomi: "ある（きます）", onyomi: "ホ" },
  112: { kunyomi: "はし（ります）", onyomi: "" },
  113: { kunyomi: "す（みます）", onyomi: "ジュウ" },
  114: { kunyomi: "そら、あ（きます）", onyomi: "クウ" },
  115: { kunyomi: "", onyomi: "シュウ" },
  116: { kunyomi: "さかな", onyomi: "" },
  117: { kunyomi: "みみ", onyomi: "" },
  118: { kunyomi: "", onyomi: "ギン" },
  119: { kunyomi: "みち", onyomi: "ドウ" },
  120: { kunyomi: "", onyomi: "エキ" }
};

// Correct kanji readings for the MLC Basic Kanji 320 set.
// Kunyomi okurigana is intentionally removed: e.g. やす（みます） -> やす.
// On-yomi are converted to hiragana and combined with the listed kun-yomi where MLC provides both.
// This is the character reading/root, not the full vocabulary word.
const kanjiSoundList = "ひと/じん/にん|ひ/か/にち|ひと/いち/いっ|ふた/に|みっ/さん|よっ/よん/よ/し|いつ/ご|むっ/ろく|なな/しち|やっ/はち|ここの/きゅう/く|とお/じゅう|つき/げつ/がつ|ひ/か|みず/すい|き/もく|かね/きん|つち/ど|ひゃく|せん|まん|えん|い/おこな/こう|き/らい|やす|み/けん|いま/こん|おお/だい/たい|ちい/こ/しょう|うえ/あ/じょう|した/さ/か|なか/ちゅう|みぎ|ひだり|やま/さん|かわ|しろ|ほん|こ|おとこ/だん|おんな/じょ|ちち/ふ|はは/ぼ|とも|さき/せん|い/う/なま/せい/しょう|まな/がく|こう|なに/なん|とき/じ|あいだ/ま/かん|わ/ふん/ぶん|はん|まい|とし/ねん|まえ/ぜん|うしろ/あと/ご|ご|な/めい|くるま/しゃ|てん|き|でん|はな/はなし/わ|た/しょく|き/き/ぶん|か/しょ|よ/どく|くに/こく|そと/がい|ご|い/はい/にゅう|だ/で/しゅつ|あめ|ひがし/とう|にし/せい/さい|みなみ/なん|きた/ほく|なが/ちょう|たか/こう|くち/こう|め|て/しゅ|あし/た|ちか/きん|あ/ゆう|はな/か|あか/あか|かみ|か|あさ|ひる|ゆう|よる/や|わたし/わたくし|いえ/か|あ/かい|しゃ|みせ/てん|の|おお|すこ/すく/しょう|ふる|あたら/しん|ひろ|やす/あん|た|し|い/こと/ごん|おも|ある/ほ|はし|す/じゅう|そら/あ/くう|しゅう|さかな|みみ|ぎん|みち/どう|えき|よう|つく/さく|つか/し|ま|ちから/りょく|ふ|こころ/しん|ぶん|げん|おと/おん|たの/がく/らく|も|うつ/えい|が/かく|りょう|り|かた/ほう|だい/たい|じ|しゅ|い|さ/きょ|ただ/しょう|た|おな|はや|あか/めい|うし/ぎゅう|にく|よ/せ|かい|し|こと/じ|こう|ば/じょう|や/おく|たび/りょ|うご/どう|べん|つよ/きょう|かんが|おく|う/ばい|はじ/し|お/しゅう|けい|あに/きょう|おとうと/だい|あね|いもうと|か/だい|よう|じ|ち/じ|ず/と|かん|えい|てつ|まち|きょう|あじ/み|ど|かぜ/ふう|よう|ちゃ|とり|どう|しつ|いろ|あお|くろ|しな/ひん|もの/ぶつ|ちゅう|い|い|もの/しゃ|びょう|いん|いそ/きゅう|はる|なつ|あき|ふゆ|おや/しん|き/せつ|とく|わか/べつ|うつ/しゃ|ま/しん|はこ/うん|ころ/てん|しつ|もん|だい|こた/とう|おし/きょう|なら/しゅう|お|し|わる|おも/じゅう|はつ|かえ|とお/かよ|あ/ひら/かい|あつ/しゅう|うた|き/つ|か|か|いぬ|ふく|た|うみ/かい|いん|ぞく|はん|の/や|さい|と/し|かん|けん|きゅう|し|けん|ない|からだ|ぜん|まわ/かい|ところ/しょ|こう|えん|り|べん|あたま|ぶ|そ|ぎょう|ふと|ひく|みじか|す|わか|よわ|かる|とお|あつ|さむ|あ/ごう|つた/でん|き/けつ|こま|かえ/へん|およ/えい|け/き|わす|よ|し|ひ|お|ひろ|す|せつ|う|と|せき|つ/れん|すわ|か/へん|の|お/ふ|はたら|のこ/ざん|しら|つづ|れん|お|ね|おそ/おく|かお|くび|こえ|と|けん|く|し|むら|たみ/みん|さん|はやし|もり|いけ|もん|くすり|あら/せん|すす|くら|ひかり|せん".split("|");
const kanjiSounds = Object.fromEntries(
  kanjiSoundList.map((sound, index) => [String(index + 1), sound])
);

window.kanjiData = [...kanjiCharacters].map((kanji, index) => {
  const no = index + 1;
  const detail = n5KanjiDetails[no] || {};
  return {
    no,
    kanji,
    level: no <= 120 ? "N5" : "N4",
    kunyomi: detail.kunyomi || "",
    onyomi: detail.onyomi || "",
    reading: [detail.kunyomi, detail.onyomi].filter(Boolean).join(" / "),
    sound: kanjiSounds[no] || "",
    meaning: ""
  };
});
