// Lesson 20
const lesson20 = {
  "vocabulary": [
    {"jp":"いります[びざが～]","romaji":"irimasu[bizaga～]","en":"need, require [a visa]","bn":"প্রয়োজন হওয়া / দরকার হওয়া"},{"jp":"しらべます","romaji":"shirabemasu","en":"check, investigate","bn":"যাচাই করা / অনুসন্ধান করা"},{"jp":"しゅうりします","romaji":"shuurishimasu","en":"repair","bn":"মেরামত করা"},{"jp":"ぼく","romaji":"boku","en":"I (an informal equivalent of わたし, used by men)","bn":"আমি (পুরুষদের অনানুষ্ঠানিক ব্যবহার)"},{"jp":"きみ","romaji":"kimi","en":"you (an informal equivalent of あなた, used to address people of equal or lower status)","bn":"তুমি / তুমি-সম্বোধন (অনানুষ্ঠানিক; সমপর্যায় বা অধস্তনকে)"},{"jp":"～くん","romaji":"～kun","en":"Mr. (an informal equivalent of ～さん, used to address people of equal or lower status; also often appended to boys' names)","bn":"~কুন (অনানুষ্ঠানিক সম্বোধন; বিশেষত ছেলেদের নামের পরে ব্যবহৃত)"},{"jp":"うん","romaji":"un","en":"yes (an informal equivalent of はい)","bn":"হ্যাঁ (অনানুষ্ঠানিক)"},{"jp":"ううん","romaji":"uun","en":"no (an informal equivalent of いいえ)","bn":"না (অনানুষ্ঠানিক)"},{"jp":"ことば","romaji":"kotoba","en":"word, language","bn":"শব্দ / ভাষা"},{"jp":"きもの","romaji":"kimono","en":"kimono (traditional Japanese attire)","bn":"কিমোনো (জাপানি ঐতিহ্যবাহী পোশাক)"},{"jp":"ビザ","romaji":"biza","en":"visa","bn":"ভিসা"},{"jp":"はじめ","romaji":"hajime","en":"the beginning","bn":"শুরু / সূচনা"},{"jp":"おわり","romaji":"owari","en":"the end of ~, The End","bn":"~এর শেষ / সমাপ্তি"},{"jp":"こっち","romaji":"kocchi","en":"this way, this place (an informal equivalent of こちら)","bn":"এদিকে / এই জায়গায় (অনানুষ্ঠানিক)"},{"jp":"そっち","romaji":"socchi","en":"that way, that place near the listener (an informal equivalent of そちら)","bn":"ওদিকে / আপনার কাছের ওই জায়গায় (অনানুষ্ঠানিক)"},{"jp":"あっち","romaji":"acchi","en":"that way, that place over there (an informal equivalent of あちら)","bn":"ওইদিকে / ওই দূরের জায়গায় (অনানুষ্ঠানিক)"},{"jp":"どっち","romaji":"docchi","en":"which one (of two things), which way, where (an informal equivalent of どちら)","bn":"দুটির মধ্যে কোনটি / কোনদিকে / কোথায় (অনানুষ্ঠানিক)"},{"jp":"みんなで","romaji":"minnade","en":"all together","bn":"সবাই মিলে / সবাই একসঙ্গে"},{"jp":"～けど","romaji":"～kedo","en":"~, but (an informal equivalent of が)","bn":"~ কিন্তু / ~, তবে (অনানুষ্ঠানিক)"},{"jp":"おなかが いっぱいです。","romaji":"onakaga ippaidesu。","en":"(I'm) full.","bn":"পেট ভরে গেছে / পেট ভরা"}
  ],
  "cpart": [
    {"jp":"よかったら","romaji":"yokattara","en":"if you like","bn":"আপনার ইচ্ছা হলে / চাইলে"},{"jp":"いろいろ","romaji":"iroiro","en":"various","bn":"বিভিন্ন / নানা রকম"}
  ],
  "country": []
};
