// Lesson 19
const lesson19 = {
  "vocabulary": [
    {"jp":"のぼります","romaji":"noborimasu","en":"climb, go up","bn":"ওঠা / উপরে ওঠা"},{"jp":"とまります[ホテルに～]","romaji":"tomarimasu[hoteruni～]","en":"stay [at a hotel]","bn":"হোটেলে থাকা"},{"jp":"そうじします","romaji":"soujishimasu","en":"clean (a room)","bn":"ঘর পরিষ্কার করা"},{"jp":"せんたくします","romaji":"sentakushimasu","en":"wash (clothes)","bn":"কাপড় ধোয়া"},{"jp":"なります","romaji":"narimasu","en":"become","bn":"হওয়া / পরিণত হওয়া"},{"jp":"ねむい","romaji":"nemui","en":"sleepy","bn":"ঘুমঘুম ভাব / তন্দ্রাচ্ছন্ন"},{"jp":"つよい","romaji":"tsuyoi","en":"strong","bn":"শক্তিশালী"},{"jp":"よわい","romaji":"yowai","en":"weak","bn":"দুর্বল"},{"jp":"れんしゅう","romaji":"renshuu","en":"practice (〜[を]します: practise)","bn":"অনুশীলন / অনুশীলন করা"},{"jp":"ゴルフ","romaji":"gorufu","en":"golf (〜をします: play golf)","bn":"গলফ / গলফ খেলা"},{"jp":"すもう","romaji":"sumou","en":"sumo wrestling (〜をします: wrestle sumo)","bn":"সুমো কুস্তি"},{"jp":"おちゃ","romaji":"ocha","en":"tea ceremony","bn":"চা অনুষ্ঠান / চা-অনুষ্ঠান"},{"jp":"ひ","romaji":"hi","en":"day, date","bn":"দিন / তারিখ"},{"jp":"ちょうし","romaji":"choushi","en":"condition","bn":"অবস্থা / শারীরিক অবস্থা"},{"jp":"いちど","romaji":"ichido","en":"once","bn":"একবার"},{"jp":"いちども","romaji":"ichidomo","en":"not once, never (used with negatives)","bn":"একবারও নয় / কখনোই নয়"},{"jp":"だんだん","romaji":"dandan","en":"gradually","bn":"ধীরে ধীরে / ক্রমশ"},{"jp":"もうすぐ","romaji":"mousugu","en":"soon","bn":"শিগগিরই / আর অল্প সময়ের মধ্যে"},{"jp":"おかげさまで","romaji":"okagesamade","en":"Thank you. (used when expressing gratitude for help received)","bn":"আপনার/সবার দয়ায় ভালো আছি / কৃতজ্ঞতা প্রকাশের ভদ্র অভিব্যক্তি"},{"jp":"でも","romaji":"demo","en":"but","bn":"কিন্তু"}
  ],
  "cpart": [
    {"jp":"かんぱい","romaji":"kanpai","en":"Bottoms up./Cheers!","bn":"চিয়ার্স! / পানীয়ের আগে বলা শুভেচ্ছা"},{"jp":"ダイエット","romaji":"daietto","en":"diet (〜をします: go on a diet)","bn":"ডায়েট / ডায়েট করা"},{"jp":"むり[な]","romaji":"muri[na]","en":"excessive, impossible","bn":"অতিরিক্ত / অসম্ভব / সাধ্যের বাইরে"},{"jp":"からだに いい","romaji":"karadani ii","en":"good for one's health","bn":"স্বাস্থ্যের জন্য ভালো"}
  ],
  "country": [
    {"jp":"とうきょうスカイツリー","romaji":"toukyousukaitsuri-","en":"Tokyo Sky Tree (broadcasting tower with observation deck in Tokyo)","bn":"টোকিও স্কাই ট্রি (টোকিওর পর্যবেক্ষণ ডেকসহ একটি সম্প্রচার টাওয়ার)"},{"jp":"かつしかほくさい","romaji":"katsushikahokusai","en":"a famous Edo-period woodblock artist and painter (1760-1849)","bn":"কাতসুশিকা হোকুসাই (এদো যুগের বিখ্যাত উডব্লক শিল্পী ও চিত্রশিল্পী, ১৭৬০–১৮৪৯)"}
  ]
};
