// Lesson 16
const lesson16 = {
  "vocabulary": [
    {"jp":"のります[でんしゃに～]","romaji":"norimasu[denshani～]","en":"ride, get on [a train]","bn":"[ট্রেনে] ওঠা / চড়া"},
    {"jp":"おります[でんしゃを～]","romaji":"orimasu[denshao～]","en":"get off [a train]","bn":"[ট্রেন থেকে] নামা"},
    {"jp":"のりかえます[でんしゃを～]","romaji":"norikaemasu[denshao～]","en":"change (train, etc.)","bn":"[ট্রেন ইত্যাদি] বদলানো / পরিবর্তন করে অন্যটিতে ওঠা"},
    {"jp":"あびます[シャワーを～]","romaji":"abimasu[shiャwa-o～]","en":"take [a shower]","bn":"[শাওয়ার] নেওয়া"},
    {"jp":"いれます","romaji":"iremasu","en":"put in, insert","bn":"ভেতরে ঢোকানো / প্রবেশ করানো"},
    {"jp":"だします","romaji":"dashimasu","en":"take out, hand in, send","bn":"বের করা / জমা দেওয়া / পাঠানো"},
    {"jp":"おろします[おかねを～]","romaji":"oroshimasu[okaneo～]","en":"withdraw [money]","bn":"[টাকা] তোলা"},
    {"jp":"はいります[だいがくに～]","romaji":"hairimasu[daigakuni～]","en":"enter [university]","bn":"[বিশ্ববিদ্যালয়ে] ভর্তি হওয়া / প্রবেশ করা"},
    {"jp":"でます[だいがくを～]","romaji":"demasu[daigakuo～]","en":"graduate from [university]","bn":"[বিশ্ববিদ্যালয় থেকে] স্নাতক হওয়া"},
    {"jp":"おします","romaji":"oshimasu","en":"push, press","bn":"ঠেলা / চাপ দেওয়া"},
    {"jp":"のみます[おさけを～]","romaji":"nomimasu[osakeo～]","en":"drink alcohol","bn":"[মদ/অ্যালকোহল] পান করা"},
    {"jp":"はじめます","romaji":"hajimemasu","en":"start, begin","bn":"শুরু করা"},
    {"jp":"けんがくします","romaji":"kengakushimasu","en":"tour, visit a place to study/observe","bn":"পরিদর্শন করে দেখা / পর্যবেক্ষণের জন্য ঘুরে দেখা"},
    {"jp":"でんわします","romaji":"denwashimasu","en":"phone","bn":"ফোন করা"},
    {"jp":"わかい","romaji":"wakai","en":"young","bn":"তরুণ / যুবক-যুবতী"},
    {"jp":"ながい","romaji":"nagai","en":"long","bn":"লম্বা / দীর্ঘ"},
    {"jp":"みじかい","romaji":"mijikai","en":"short","bn":"খাটো / ছোট / সংক্ষিপ্ত"},
    {"jp":"あかるい","romaji":"akarui","en":"bright, light","bn":"উজ্জ্বল / আলোকিত"},
    {"jp":"くらい","romaji":"kurai","en":"dark","bn":"অন্ধকার / অনুজ্জ্বল"},
    {"jp":"からだ","romaji":"karada","en":"body, health","bn":"শরীর / দেহ"},
    {"jp":"あたま","romaji":"atama","en":"head, brain","bn":"মাথা / মস্তিষ্ক"},
    {"jp":"かみ","romaji":"kami","en":"hair","bn":"চুল"},
    {"jp":"かお","romaji":"kao","en":"face","bn":"মুখমণ্ডল / মুখ"},
    {"jp":"め","romaji":"me","en":"eye","bn":"চোখ"},
    {"jp":"みみ","romaji":"mimi","en":"ear","bn":"কান"},
    {"jp":"はな","romaji":"hana","en":"nose","bn":"নাক"},
    {"jp":"くち","romaji":"kuchi","en":"mouth","bn":"মুখ"},
    {"jp":"は","romaji":"ha","en":"tooth","bn":"দাঁত"},
    {"jp":"おなか","romaji":"onaka","en":"stomach","bn":"পেট"},
    {"jp":"あし","romaji":"ashi","en":"leg, foot","bn":"পা"},
    {"jp":"せ","romaji":"se","en":"height","bn":"উচ্চতা / দৈহিক উচ্চতা"},
    {"jp":"サービス","romaji":"sa-bisu","en":"service","bn":"সেবা / পরিষেবা"},
    {"jp":"ジョギング","romaji":"jiョgingu","en":"jogging (〜をします: jog)","bn":"জগিং / হালকা দৌড়ানো"},
    {"jp":"シャワー","romaji":"shiャwa-","en":"shower","bn":"শাওয়ার"},
    {"jp":"みどり","romaji":"midori","en":"green, greenery","bn":"সবুজ / সবুজ গাছপালা"},
    {"jp":"[お]てら","romaji":"[o]tera","en":"Buddhist temple","bn":"বৌদ্ধ মন্দির"},
    {"jp":"じんじゃ","romaji":"jinja","en":"Shinto shrine","bn":"শিন্তো উপাসনালয় / শিন্তো মন্দির"},
    {"jp":"～ばん","romaji":"～ban","en":"number ~","bn":"~ নম্বর"},
    {"jp":"どうやって","romaji":"douyatte","en":"in what way, how","bn":"কীভাবে / কোন উপায়ে"},
    {"jp":"どの～","romaji":"dono～","en":"which ~ (used for three or more)","bn":"কোন ~টি (তিন বা তার বেশি থেকে)"},
    {"jp":"どれ","romaji":"dore","en":"which one (of three or more things)","bn":"তিন বা তার বেশি জিনিসের মধ্যে কোনটি"}
  ],
  "cpart": [
    {"jp":"すごいですね。","romaji":"sugoidesune。","en":"That's amazing!","bn":"দারুণ! / অসাধারণ!"},
    {"jp":"[いいえ、] まだまだです。","romaji":"[iie、] madamadadesu。","en":"[No,] I still have a long way to go.","bn":"[না,] এখনও অনেক কিছু শেখার বাকি।"},
    {"jp":"おひきだしですか。","romaji":"ohikidashidesuka。","en":"Are you making a withdrawal?","bn":"আপনি কি টাকা তুলছেন?"},
    {"jp":"まず","romaji":"mazu","en":"first of all","bn":"প্রথমে / সর্বপ্রথম"},
    {"jp":"つぎに","romaji":"tsugini","en":"next, as a next step","bn":"এরপর / পরবর্তী ধাপে"},
    {"jp":"キャッシュカード","romaji":"kiャsshiュka-do","en":"cash dispensing card","bn":"ক্যাশ কার্ড / এটিএম কার্ড"},
    {"jp":"あんしょうばんごう","romaji":"anshoubangou","en":"personal identification number, PIN","bn":"ব্যক্তিগত শনাক্তকরণ নম্বর (PIN)"},
    {"jp":"きんがく","romaji":"kingaku","en":"amount of money","bn":"টাকার পরিমাণ"},
    {"jp":"かくにん","romaji":"kakunin","en":"confirmation (〜します: confirm)","bn":"নিশ্চিতকরণ / নিশ্চিত করা"},
    {"jp":"ボタン","romaji":"botan","en":"button","bn":"বোতাম"}
  ],
  "country": [
    {"jp":"JR","romaji":"JR","en":"Japan Railways","bn":"জাপান রেলওয়েজ / জেআর"},
    {"jp":"ゆきまつり","romaji":"yukimatsuri","en":"Snow Festival","bn":"তুষার উৎসব / স্নো ফেস্টিভ্যাল"},
    {"jp":"バンドン","romaji":"bandon","en":"Bandung (in Indonesia)","bn":"বান্দুং (ইন্দোনেশিয়া)"},
    {"jp":"フランケン","romaji":"furanken","en":"Franken (in Germany)","bn":"ফ্রাঙ্কেন (জার্মানি)"},
    {"jp":"ベラクルス","romaji":"berakurusu","en":"Veracruz (in Mexico)","bn":"ভেরাক্রুজ (মেক্সিকো)"},
    {"jp":"うめだ","romaji":"umeda","en":"a district in Osaka","bn":"ওসাকার একটি এলাকা"},
    {"jp":"だいがくまえ","romaji":"daigakumae","en":"a fictitious bus stop","bn":"কাল্পনিক বাসস্টপ"}
  ]
};
