// Lesson 23
const lesson23 = {
  "vocabulary": [
    {"jp":"ききます[せんせいに～]","romaji":"kikimasu[senseini～]","en":"ask [the teacher]","bn":"[শিক্ষককে] জিজ্ঞাসা করা"},{"jp":"まわします","romaji":"mawashimasu","en":"turn","bn":"ঘোরানো"},{"jp":"ひきます","romaji":"hikimasu","en":"pull","bn":"টানা"},{"jp":"かえます","romaji":"kaemasu","en":"change","bn":"বদলানো"},{"jp":"さわります[ドアに～]","romaji":"sawarimasu[doani～]","en":"touch [a door]","bn":"[দরজা] স্পর্শ করা"},{"jp":"でます[おつりが～]","romaji":"demasu[otsuriga～]","en":"[change] come out","bn":"[ফেরত টাকা] বের হওয়া"},{"jp":"あるきます","romaji":"arukimasu","en":"walk","bn":"হাঁটা"},{"jp":"わたります[はしを～]","romaji":"watarimasu[hashio～]","en":"cross [a bridge]","bn":"[সেতু] পার হওয়া"},{"jp":"まがります[みぎへ～]","romaji":"magarimasu[migihe～]","en":"turn [to the right]","bn":"[ডান দিকে] মোড় নেওয়া"},{"jp":"さびしい","romaji":"sabishii","en":"lonely","bn":"একাকী / নিঃসঙ্গ"},{"jp":"[お]ゆ","romaji":"[o]yu","en":"hot water","bn":"গরম পানি"},{"jp":"おと","romaji":"oto","en":"sound","bn":"শব্দ / আওয়াজ"},{"jp":"サイズ","romaji":"saizu","en":"size","bn":"মাপ / সাইজ"},{"jp":"こしょう","romaji":"koshou","en":"breakdown (〜します: break down)","bn":"বিকল হওয়া / নষ্ট হয়ে যাওয়া"},{"jp":"みち","romaji":"michi","en":"road, way","bn":"রাস্তা / পথ"},{"jp":"こうさてん","romaji":"kousaten","en":"crossroads","bn":"চৌরাস্তা / সড়কের মোড়"},{"jp":"しんごう","romaji":"shingou","en":"traffic lights","bn":"ট্রাফিক সিগন্যাল / বাতি"},{"jp":"かど","romaji":"kado","en":"corner","bn":"কোণ / রাস্তার মোড়"},{"jp":"はし","romaji":"hashi","en":"bridge","bn":"সেতু / ব্রিজ"},{"jp":"ちゅうしゃじょう","romaji":"chuushajou","en":"car park, parking lot","bn":"গাড়ি পার্কিং / পার্কিং লট"},{"jp":"たてもの","romaji":"tatemono","en":"building","bn":"ভবন / বিল্ডিং"},{"jp":"なんかいも","romaji":"nankaimo","en":"many times","bn":"অনেকবার / বহুবার"},{"jp":"～め","romaji":"～me","en":"the -th (indicating order)","bn":"ক্রম বোঝাতে ব্যবহৃত ~তম"}
  ],
  "cpart": [],
  "country": [
    {"jp":"しょうとくたいし","romaji":"shoutokutaishi","en":"Prince Shotoku (574-622)","bn":"প্রিন্স শোতোকু (৫৭৪–৬২২)"},{"jp":"ほうりゅうじ","romaji":"houryuuji","en":"Horyuji Temple, a temple in Nara Prefecture built by Prince Shotoku at the beginning of the 7th century","bn":"হোরিউজি মন্দির (নারা প্রিফেকচারের ঐতিহাসিক বৌদ্ধ মন্দির)"},{"jp":"げんきちゃ","romaji":"genkicha","en":"a fictitious tea","bn":"কাল্পনিক চা"},{"jp":"ほんだえき","romaji":"hondaeki","en":"a fictitious station","bn":"কাল্পনিক স্টেশন"},{"jp":"としょかんまえ","romaji":"toshokanmae","en":"a fictitious bus stop","bn":"কাল্পনিক বাসস্টপ"}
  ]
};
