// Lesson 7
const lesson7 = {
  "vocabulary": [
    {"jp":"きります","romaji":"kirimasu","en":"cut, slice","bn":"কাটা / টুকরো করা"},{"jp":"おくります","romaji":"okurimasu","en":"send","bn":"পাঠানো / প্রেরণ করা"},{"jp":"あげます","romaji":"agemasu","en":"give","bn":"দেওয়া / উপহার দেওয়া"},{"jp":"もらいます","romaji":"moraimasu","en":"receive","bn":"পাওয়া / গ্রহণ করা"},{"jp":"かします","romaji":"kashimasu","en":"lend","bn":"ধার দেওয়া"},{"jp":"かります","romaji":"karimasu","en":"borrow","bn":"ধার নেওয়া"},{"jp":"おしえます","romaji":"oshiemasu","en":"teach","bn":"শেখানো / শিক্ষা দেওয়া"},{"jp":"ならいます","romaji":"naraimasu","en":"learn","bn":"শেখা / কারও কাছ থেকে শেখা"},{"jp":"かけます[でんわを～]","romaji":"kakemasu[denwa o～]","en":"make [a telephone call]","bn":"[ফোন] করা"},{"jp":"て","romaji":"te","en":"hand, arm","bn":"হাত"},{"jp":"はし","romaji":"hashi","en":"chopsticks","bn":"চপস্টিক / খাওয়ার কাঠি"},{"jp":"スプーン","romaji":"supūn","en":"spoon","bn":"চামচ"},{"jp":"ナイフ","romaji":"naifu","en":"knife","bn":"ছুরি"},{"jp":"フォーク","romaji":"fōku","en":"fork","bn":"কাঁটা চামচ"},{"jp":"はさみ","romaji":"hasami","en":"scissors","bn":"কাঁচি"},{"jp":"パソコン","romaji":"pasokon","en":"personal computer","bn":"ব্যক্তিগত কম্পিউটার / পিসি"},{"jp":"けいたい[でんわ] or ケータイ","romaji":"keitai[denwa]","en":"mobile phone, cell phone","bn":"মোবাইল ফোন"},{"jp":"メール","romaji":"mēru","en":"e-mail","bn":"ই-মেইল"},{"jp":"ねんがじょう","romaji":"nengajō","en":"New Year's greeting card","bn":"নববর্ষের শুভেচ্ছা কার্ড"},{"jp":"パンチ","romaji":"panchi","en":"punch","bn":"কাগজে ছিদ্র করার যন্ত্র / পাঞ্চ"},{"jp":"ホッチキス","romaji":"hocchikisu","en":"stapler","bn":"স্ট্যাপলার"},{"jp":"セロテープ","romaji":"serotēpu","en":"Sellotape, Scotch tape, clear tape","bn":"স্বচ্ছ আঠালো টেপ / সেলোটেপ"},{"jp":"けしゴム","romaji":"keshigomu","en":"rubber, eraser","bn":"রাবার / ইরেজার"},{"jp":"かみ","romaji":"kami","en":"paper","bn":"কাগজ"},{"jp":"はな","romaji":"hana","en":"flower, blossom","bn":"ফুল"},{"jp":"シャツ","romaji":"shatsu","en":"shirt","bn":"শার্ট"},{"jp":"プレゼント","romaji":"purezento","en":"present, gift","bn":"উপহার"},{"jp":"にもつ","romaji":"nimotsu","en":"luggage, baggage, parcel","bn":"লাগেজ / মালপত্র / পার্সেল"},{"jp":"おかね","romaji":"okane","en":"money","bn":"টাকা / অর্থ"},{"jp":"きっぷ","romaji":"kippu","en":"ticket","bn":"টিকিট"},{"jp":"クリスマス","romaji":"kurisumasu","en":"Christmas","bn":"বড়দিন / ক্রিসমাস"},{"jp":"ちち","romaji":"chichi","en":"(my) father","bn":"আমার বাবা"},{"jp":"はは","romaji":"haha","en":"(my) mother","bn":"আমার মা"},{"jp":"おとうさん","romaji":"otōsan","en":"(someone else's) father (also used to address one's own father)","bn":"অন্যের বাবা / নিজের বাবাকে সম্বোধনে বাবা"},{"jp":"おかあさん","romaji":"okāsan","en":"(someone else's) mother (also used to address one's own mother)","bn":"অন্যের মা / নিজের মাকে সম্বোধনে মা"},{"jp":"もう","romaji":"mō","en":"already","bn":"ইতিমধ্যে / এরই মধ্যে"},{"jp":"まだ","romaji":"mada","en":"not yet","bn":"এখনও নয় / এখনও"},{"jp":"これから","romaji":"korekara","en":"from now on, soon","bn":"এখন থেকে / এখন থেকে শিগগির"}
  ],
  "cpart": [
    {"jp":"[～]って すてきですね。","romaji":"[～]tte suteki desu ne。","en":"What a nice [~]!","bn":"[~] কী সুন্দর! / [~] দারুণ তো!"},{"jp":"いらっしゃい。","romaji":"irasshai。","en":"Do come in.","bn":"এসো / আসুন / স্বাগতম"},{"jp":"どうぞ おあがりください。","romaji":"dōzo oagari kudasai。","en":"Won't you come in?","bn":"দয়া করে ভিতরে আসুন / ভেতরে প্রবেশ করুন"},{"jp":"しつれいします。","romaji":"shitsurei shimasu。","en":"(said before entering someone's house)","bn":"কারও বাড়িতে ঢোকার আগে বলা ভদ্র অভিব্যক্তি: অনুমতি নিয়ে ঢুকছি / মাফ করবেন"},{"jp":"[～を] どうぞ。","romaji":"[～o] dōzo。","en":"Won't you have [~]? (used when offering something)","bn":"[~] নিন / গ্রহণ করুন"},{"jp":"いただきます。","romaji":"itadakimasu。","en":"Thank you. I accept. (said before eating or drinking)","bn":"খাওয়া বা পান করা শুরু করার আগে কৃতজ্ঞতা জানিয়ে বলা ভদ্র অভিব্যক্তি"},{"jp":"ごちそうさま[でした]。","romaji":"gochisōsama[deshita]。","en":"That was delicious. (said after eating or drinking)","bn":"খাওয়া বা পান করার পর কৃতজ্ঞতা জানানোর ভদ্র অভিব্যক্তি"}
  ],
  "country": [
    {"jp":"スペイン","romaji":"supein","en":"Spain","bn":"স্পেন"}
  ]
};
