// Lesson 22
const lesson22 = {
  "vocabulary": [
    {"jp":"きます","romaji":"kimasu","en":"put on (a shirt, etc.)","bn":"পরা (শার্ট, জামা ইত্যাদি)"},{"jp":"はきます","romaji":"hakimasu","en":"put on (shoes, trousers, etc.)","bn":"পরা (জুতা, প্যান্ট ইত্যাদি)"},{"jp":"かぶります","romaji":"kaburimasu","en":"put on (a hat, etc.)","bn":"মাথায় পরা (টুপি ইত্যাদি)"},{"jp":"かけます[めがねを～]","romaji":"kakemasu[meganeo～]","en":"put on [glasses]","bn":"[চশমা] পরা"},{"jp":"します[ネクタイを～]","romaji":"shimasu[nekutaio～]","en":"put on [tie]","bn":"[টাই] পরা"},{"jp":"うまれます","romaji":"umaremasu","en":"be born","bn":"জন্মগ্রহণ করা / জন্মানো"},{"jp":"わたしたち","romaji":"watashitachi","en":"we","bn":"আমরা"},{"jp":"コート","romaji":"ko-to","en":"coat","bn":"কোট"},{"jp":"セーター","romaji":"se-ta-","en":"sweater","bn":"সোয়েটার"},{"jp":"スーツ","romaji":"su-tsu","en":"suit","bn":"স্যুট"},{"jp":"ぼうし","romaji":"boushi","en":"hat, cap","bn":"টুপি / ক্যাপ"},{"jp":"めがね","romaji":"megane","en":"glasses","bn":"চশমা"},{"jp":"ケーキ","romaji":"ke-ki","en":"cake","bn":"কেক"},{"jp":"[お]べんとう","romaji":"[o]bentou","en":"box lunch","bn":"বক্স লাঞ্চ / খাবারের প্যাকেট"},{"jp":"ロボット","romaji":"robotto","en":"robot","bn":"রোবট"},{"jp":"ユーモア","romaji":"yu-moa","en":"humor","bn":"রসবোধ / হাস্যরস"},{"jp":"つごう","romaji":"tsugou","en":"convenience","bn":"সুবিধা / সুবিধাজনকতা"},{"jp":"よく","romaji":"yoku","en":"often","bn":"প্রায়ই / প্রায়শই"}
  ],
  "cpart": [
    {"jp":"えーと","romaji":"e-to","en":"well, let me see","bn":"উম্… / আচ্ছা, দেখি…"},{"jp":"おめでとう[ございます]。","romaji":"omedetou[gozaimasu]。","en":"Congratulations. (used on birthdays, at weddings, New Year's Day, etc.)","bn":"অভিনন্দন। (জন্মদিন, বিয়ে, নববর্ষ ইত্যাদিতে)"},{"jp":"おさがしですか。","romaji":"osagashidesuka。","en":"Are you looking for ~?","bn":"আপনি কি ~ খুঁজছেন?"},{"jp":"では","romaji":"deha","en":"Well then,","bn":"আচ্ছা তাহলে / তাহলে"},{"jp":"こちら","romaji":"kochira","en":"this (polite equivalent of これ)","bn":"এটি / এটা (ভদ্র রূপ)"},{"jp":"やちん","romaji":"yachin","en":"rent","bn":"বাড়িভাড়া / ভাড়া"},{"jp":"ダイニングキッチン","romaji":"dainingukicchin","en":"kitchen with a dining area","bn":"খাওয়ার জায়গাসহ রান্নাঘর"},{"jp":"わしつ","romaji":"washitsu","en":"Japanese-style room","bn":"জাপানি ধাঁচের ঘর"},{"jp":"おしいれ","romaji":"oshiire","en":"Japanese-style closet","bn":"জাপানি ধাঁচের দেয়াল-আলমারি / স্টোরেজ কুঠরি"},{"jp":"ふとん","romaji":"futon","en":"Japanese-style mattress and quilt","bn":"জাপানি ধাঁচের গদি ও লেপ / ফুতোন"}
  ],
  "country": [
    {"jp":"パリ","romaji":"pari","en":"Paris","bn":"প্যারিস"},{"jp":"ばんりのちょうじょう","romaji":"banrinochoujou","en":"the Great Wall of China","bn":"চীনের মহাপ্রাচীর / গ্রেট ওয়াল"},{"jp":"みんなのアンケート","romaji":"minnanoanke-to","en":"title of a fictitious questionnaire","bn":"কাল্পনিক প্রশ্নপত্রের শিরোনাম"}
  ]
};
