// Lesson 18
const lesson18 = {
  "vocabulary": [
    {"jp":"できます","romaji":"dekimasu","en":"be able to, can","bn":"পারা / সক্ষম হওয়া"},{"jp":"あらいます","romaji":"araimasu","en":"wash","bn":"ধোয়া"},{"jp":"ひきます","romaji":"hikimasu","en":"play (stringed instrument, piano)","bn":"বাদ্যযন্ত্র / পিয়ানো বাজানো"},{"jp":"うたいます","romaji":"utaimasu","en":"sing","bn":"গান গাওয়া"},{"jp":"あつめます","romaji":"atsumemasu","en":"collect, gather","bn":"সংগ্রহ করা / জড়ো করা"},{"jp":"すてます","romaji":"sutemasu","en":"throw away","bn":"ফেলে দেওয়া"},{"jp":"かえます","romaji":"kaemasu","en":"exchange, change","bn":"বদলানো / বিনিময় করা"},{"jp":"うんてんします","romaji":"untenshimasu","en":"drive","bn":"গাড়ি চালানো"},{"jp":"よやくします","romaji":"yoyakushimasu","en":"reserve, book","bn":"আগে থেকে সংরক্ষণ করা / বুক করা"},{"jp":"ピアノ","romaji":"piano","en":"piano","bn":"পিয়ানো"},{"jp":"～メートル","romaji":"～me-toru","en":"~ meter","bn":"~ মিটার"},{"jp":"げんきん","romaji":"genkin","en":"cash","bn":"নগদ টাকা"},{"jp":"しゅみ","romaji":"shumi","en":"hobby","bn":"শখ"},{"jp":"にっき","romaji":"nikki","en":"diary","bn":"ডায়েরি"},{"jp":"おいのり","romaji":"oinori","en":"prayer (〜をします: pray)","bn":"প্রার্থনা / প্রার্থনা করা"},{"jp":"かちょう","romaji":"kachou","en":"section head","bn":"সেকশন প্রধান / বিভাগীয় প্রধান"},{"jp":"ぶちょう","romaji":"buchou","en":"department head","bn":"বিভাগের প্রধান"},{"jp":"しゃちょう","romaji":"shachou","en":"company president","bn":"কোম্পানির প্রেসিডেন্ট / ব্যবস্থাপনা প্রধান"},{"jp":"どうぶつ","romaji":"doubutsu","en":"animal","bn":"প্রাণী"},{"jp":"うま","romaji":"uma","en":"horse","bn":"ঘোড়া"},{"jp":"インターネット","romaji":"inta-netto","en":"the Internet","bn":"ইন্টারনেট"}
  ],
  "cpart": [
    {"jp":"とくに","romaji":"tokuni","en":"especially","bn":"বিশেষ করে"},{"jp":"へえ","romaji":"hee","en":"What! Really! (used when expressing surprise)","bn":"ওহ! সত্যি!"},{"jp":"それは おもしろいですね。","romaji":"soreha omoshiroidesune。","en":"That's interesting, isn't it?","bn":"সেটা তো বেশ মজার / আকর্ষণীয়, তাই না?"},{"jp":"なかなか","romaji":"nakanaka","en":"not easily (used with negatives)","bn":"সহজে নয় / সহজে হয় না (নেতিবাচক বাক্যে)"},{"jp":"ほんとうですか。","romaji":"hontoudesuka。","en":"Really?","bn":"সত্যি?"},{"jp":"ぜひ","romaji":"zehi","en":"by all means, really","bn":"অবশ্যই / অবশ্যই করবেন"}
  ],
  "country": [
    {"jp":"ふるさと","romaji":"furusato","en":"Furusato (a song title meaning 'Home Town')","bn":"ফুরুসাতো (‘নিজ শহর / স্বদেশ’ অর্থের একটি গানের নাম)"},{"jp":"ビートルズ","romaji":"bi-toruzu","en":"the Beatles (a famous British pop group)","bn":"দ্য বিটলস (বিখ্যাত ব্রিটিশ পপ ব্যান্ড)"},{"jp":"あきはばら","romaji":"akihabara","en":"a district in Tokyo","bn":"টোকিওর একটি এলাকা / ইলেকট্রনিক্সের জন্য বিখ্যাত শপিং এলাকা"}
  ]
};
